I18n apply discount code
strangerstudios/paid-memberships-pro pull request #1663
Opened 2021-05-24 13:10 UTC by mircobabini

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fix to applydiscountcode.php where javascript is written by php and not always escaped with _pmpro_no_quotes_. This where causing issues with i18n as reported in the issue below.

Resolves 1662.

### How to test the changes in this Pull Request:

1. Check the linked issue which contains the explanation.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

2021-06-21 21:45 UTC, sc0ttkclark commented on services/applydiscountcode.php
> +				jQuery('#pmpro_level_cost').html('<p><?php pmpro_no_quotes(sprintf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code), array('"', "'", "\
```suggestion
				jQuery('#pmpro_level_cost').html('<p><?php echo esc_js( sprintf(__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ) );?></p><p><?php echo esc_js( pmpro_getLevelCost( $code_level ) )?><?php echo esc_js( pmpro_getLevelExpiration( $code_level ) ); ?></p>');
```

2021-06-21 21:45 UTC, sc0ttkclark commented on services/applydiscountcode.php
> +				jQuery('#pmpro_level_cost').html('<p><?php pmpro_no_quotes(sprintf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code), array('"', "'", "\
```suggestion
				jQuery('#pmpro_level_cost').html('<p><?php echo esc_js( sprintf(__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ) ); ?></p><p><?php echo esc_js( pmpro_getLevelsCost( $code_levels ) ); ?><?php echo esc_js( pmpro_getLevelsExpiration( $code_levels ) ); ?></p>');
```

2021-06-21 21:46 UTC, sc0ttkclark reviewed
@mircobabini Can you retest with the esc_js changes I've suggested?

2021-06-22 10:48 UTC, mircobabini reviewed
Works great! Thank you @sc0ttkclark, nice usage of `esc_js`.

2021-06-24 15:13 UTC, sc0ttkclark requested changes
@ideadude This one needs a little more thought because the esc_js will cause entities for the HTML in the <strong> tags

2021-06-24 15:15 UTC, sc0ttkclark commented on services/applydiscountcode.php
> +				jQuery('#pmpro_level_cost').html('<p><?php echo esc_js( sprintf(__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ) ); ?></p><p><?php ec
```suggestion
				jQuery('#pmpro_level_cost').html('<p><?php printf( esc_attr__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ); ?></p><p><?php echo esc_js( pmpro_getLevelCost( $code_level ) . pmpro_getLevelExpiration( $code_level ) ); ?></p>');
```

2021-06-24 15:19 UTC, merged

2021-06-24 15:22 UTC, sc0ttkclark commented
I'll follow up on this PR to fix the escaping problem

2021-06-24 15:29 UTC, mircobabini commented
@sc0ttkclark right. We must use `addslashes`.

```
  | original > Testo con un'apostrofo <strong>dove non andrebbe messo</strong>.
  | esc_js > Testo con un\'apostrofo &lt;strong&gt;dove non andrebbe messo&lt;/strong&gt;.
  | esc_html > Testo con un&#039;apostrofo &lt;strong&gt;dove non andrebbe messo&lt;/strong&gt;.
  | esc_attr > Testo con un&#039;apostrofo &lt;strong&gt;dove non andrebbe messo&lt;/strong&gt;.
  | esc_sql > Testo con un\'apostrofo <strong>dove non andrebbe messo</strong>. <<< this one works!
  | addslashes > Testo con un\'apostrofo <strong>dove non andrebbe messo</strong>. <<< this one works!
```

These are some tests on a string with apostrophe and html tags. The last one is what we want.

2021-06-24 15:56 UTC, sc0ttkclark commented
@mircobabini after further digging on this -- the combination of needs here for escaping, but keeping HTML, and removing line breaks so it won't break JS necessitates usage of `wp_json_encode`. I cleaned up this section of the code so it's easier to maintain and easier to see what's going on and why in https://github.com/strangerstudios/paid-memberships-pro/pull/1679