Stripe products prices
strangerstudios/paid-memberships-pro pull request #1824
Opened 2021-10-20 18:47 UTC by dparker1005

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:
Start using a single Stripe product per level and a single Stripe Price per payment amount.

Also contains changes to make the `process` method easier to follow for each page load and reduce "magic" properties stored in the MemberOrder.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-11-24 01:56 UTC, sc0ttkclark requested changes
Some quick changes here, looking good so far. I'll do more review later too

2021-11-24 01:56 UTC, sc0ttkclark commented on classes/gateways/class.pmprogateway_stripe.php
> +				$order->error      = __( "Error processing setup intent.", 'paid-memberships-pro' ) . " " . $setup_intent;
```suggestion
				$order->error      = __( 'Error processing setup intent.', 'paid-memberships-pro' ) . ' ' . $setup_intent;
```

2021-11-24 01:56 UTC, sc0ttkclark commented on classes/gateways/class.pmprogateway_stripe.php
> +					$order->error      = __( "Error processing payment intent.", 'paid-memberships-pro' ) . " " . $payment_intent;
```suggestion
					$order->error      = __( 'Error processing payment intent.', 'paid-memberships-pro' ) . ' ' . $payment_intent;
```

2021-11-24 01:56 UTC, sc0ttkclark commented on classes/gateways/class.pmprogateway_stripe.php
> +					$order->error      = __( "Error retrieving payment method.", 'paid-memberships-pro' );
```suggestion
					$order->error      = __( 'Error retrieving payment method.', 'paid-memberships-pro' );
```

2021-11-24 01:56 UTC, sc0ttkclark commented on classes/gateways/class.pmprogateway_stripe.php
> +					$order->error      = __( "Error updating default payment method.", 'paid-memberships-pro' ) . " " . $customer;
```suggestion
					$order->error      = __( 'Error updating default payment method.', 'paid-memberships-pro' ) . ' ' . $customer;
```

2021-11-24 01:56 UTC, sc0ttkclark commented on classes/gateways/class.pmprogateway_stripe.php
> +					$order->error      = __( "Error creating subscription for customer.", 'paid-memberships-pro' );
```suggestion
					$order->error      = __( 'Error creating subscription for customer.', 'paid-memberships-pro' );
```

2021-12-02 19:32 UTC, sc0ttkclark approved these changes

2021-12-03 15:37 UTC, ideadude commented on classes/gateways/class.pmprogateway_stripe.php
> +			'name' => $level->name,
The reference doesn't mention anything. https://stripe.com/docs/api/products/create#create_product-name

Playing around with names and description in the Stripe dashboard, it seems like any unicode character is allowed, including emojis, etc. When I tried to add HTML, it was included but not rendered in the Stripe dashboard. So they might be escaping that.

I think for now, let's trust Stripe to handle it.

2021-12-03 15:44 UTC, merged