Story 302 Customize section titles on account page
strangerstudios/paid-memberships-pro pull request #2459
Opened 2023-05-01 20:53 UTC by MaximilianoRicoTabo

* Adds support to pass a title attribute to [pmpro_account] shortcode when it has a single section as param.
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/1678457/235527950-a4ddbd4a-130d-4d82-aa2d-0958d74ceebd.png">
<img width="753" alt="image" src="https://user-images.githubusercontent.com/1678457/235527998-9b2cd8e6-55c9-4fc1-bdc5-f9240dc2e8f5.png">
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/1678457/235528113-1e2760d0-7c52-4620-9611-5df37d70a2b8.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/1678457/235528144-7ef375a2-521d-48ab-bd8b-9b88efb284c2.png">
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/1678457/235528212-1a060975-6aca-49f1-ade6-b52bb72457b3.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/1678457/235528246-2c264b8c-78d4-49ef-8b9b-d87d66a87252.png">

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Extract from shortcode attributes the "title" and if it exists and meet conditions use it to render given single section. Otherwise ignore it and use default.

Resolves XXX.

### How to test the changes in this Pull Request:

1. Create a page or post
2. Add the shortcode and play with different combinations, one section, more than one, add title, make it empty, don't add it.
3. Check results.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
 Adds support to pass a title attribute to [pmpro_account] shortcode when it has a single section as a param.

2023-05-01 20:57 UTC, MaximilianoRicoTabo commented
submitted as as a draft. It lacks the part regarding customize gutenberg which will go in the next commit

2023-05-02 15:58 UTC, dparker1005 requested changes
Looks good so far! The one note that I have is that the first parameter passed to l18n functions should always be a literal string instead of a variable. Passing a variable could interfere with the automatic parsing of the plugin files when creating translation files.

I included a sample fix of this for the Membership section. The fixes should be similar for the other three

2023-05-02 15:58 UTC, dparker1005 commented on shortcodes/pmpro_account.php
> +			$membership_title = $title_param ? $title_param : 'My Membership';
```suggestion
			$membership_title = $title_param ? $title_param : __( 'My Membership', 'paid-memberships-pro );

```

2023-05-03 11:47 UTC, MaximilianoRicoTabo commented on shortcodes/pmpro_account.php
> +				<h3><?php esc_html_e($membership_title, 'paid-memberships-pro' );?></h3>
done, thanks

2023-05-04 16:40 UTC, dparker1005 approved these changes

2023-05-25 15:07 UTC, merged