Fixed always redirect to login page
strangerstudios/paid-memberships-pro pull request #2971
Opened 2024-04-23 10:51 UTC by andrewlimaza

* BUG FIX: Fixed an issue where the redirect would always redirect to the login page.

The issue here was we were ommitting the redirect value entirely from the $login_form_array which would then default to setting a $redirect_to value of the REQUEST URI and it would always redirect to that URL based on the wp_login_form defaults when that parameter was missing.

This fix, fixes issues for custom redirects (snippets) as well as the Member Homepages Add On.

Setting the `redirect` argument to false by default as Paid Memberships Pro handles it's own redirects during the login process and this returns the expected functionality.

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

2024-04-26 16:07 UTC, dparker1005 approved these changes

2024-04-26 16:13 UTC, dparker1005 requested changes
According to the WP developer docs, the `redirect` argument should always be a string:
https://developer.wordpress.org/reference/functions/wp_login_form/

In the `wp_login_form()` function itself, it is clear that `redirect` is expected to be a string as well, so passing `false` may throw warnings in recent versions of PHP:
https://github.com/WordPress/wordpress-develop/blob/a2bb04fc352f0b58a822ff83f3bd8ca6fed11757/src/wp-includes/general-template.php#L627

Is there a better "default" redirect argument that we can pass here?

2024-04-29 14:26 UTC, andrewlimaza commented
> According to the WP developer docs, the `redirect` argument should always be a string: https://developer.wordpress.org/reference/functions/wp_login_form/
> 
> In the `wp_login_form()` function itself, it is clear that `redirect` is expected to be a string as well, so passing `false` may throw warnings in recent versions of PHP: https://github.com/WordPress/wordpress-develop/blob/a2bb04fc352f0b58a822ff83f3bd8ca6fed11757/src/wp-includes/general-template.php#L627
> 
> Is there a better "default" redirect argument that we can pass here?

I moved over to passing an empty string instead of false. This will still work with the `esc_url` call that eventually happens by the `wp_login_form`.

2024-05-02 09:19 UTC, andrewlimaza commented
Added blocking next release tag back to this as it's interfering with Member Homepages and a bunch of custom code that redirects members to specific pages on login.

2024-05-08 13:54 UTC, dparker1005 approved these changes

2024-05-08 16:47 UTC, merged