Add Group ID to Level Settings page
strangerstudios/paid-memberships-pro pull request #2978
Opened 2024-04-26 11:20 UTC by andrewlimaza

* ENHANCEMENT: Added group ID value to the menu location within the Level Settings page. This makes it easier to identify the group's ID for developers and future features that may need this.

The idea of putting this to the right of the name is to try and not clutter up the group names and make it easily visible without clicking around to get this data.

**Screenshots**
![Screenshot 2024-04-26 at 13 15 05](https://github.com/strangerstudios/paid-memberships-pro/assets/12629136/f1fbddd6-94fe-4335-a115-c4ab6c6aa390)

![Screenshot 2024-04-26 at 13 15 15](https://github.com/strangerstudios/paid-memberships-pro/assets/12629136/e6566881-bc6a-4be5-b17b-926c7f26022e)

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

2024-04-26 16:20 UTC, dparker1005 approved these changes

2024-04-29 13:42 UTC, andrewlimaza commented on adminpages/membershiplevels.php
> +								<?php echo esc_html( $level_group->name ) . '<small>'. sprintf( esc_html( 'ID: %d', 'paid-memberships-pro' ), $level_group->id ) . '</small>'; ?>
Thanks for catching that, I made it translatable by changing `esc_html` to `esc_html__`

2024-05-07 13:16 UTC, kimcoleman approved these changes

2024-05-07 13:34 UTC, dparker1005 requested changes

2024-05-07 13:34 UTC, dparker1005 commented on adminpages/membershiplevels.php
> +								<?php echo esc_html( $level_group->name ) . '<small>'. sprintf( esc_html__( 'ID: %d', 'paid-memberships-pro' ), $level_group->id ) . '</small>'; ?>
```suggestion
								<?php echo esc_html( $level_group->name ) . '<small>'. sprintf( esc_html__( 'ID: %d', 'paid-memberships-pro' ), esc_html( $level_group->id ) ) . '</small>'; ?>
```

2024-05-08 16:52 UTC, merged