* Remove members only option from dropdown
strangerstudios/paid-memberships-pro pull request #3147
Opened 2024-09-24 21:43 UTC by MaximilianoRicoTabo

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

 Hook on Access Plan action to add a jQuery snippet that removes the not wanted option in case streamline setting is checked.

Resolves #3088 

### How to test the changes in this Pull Request:

See related issue for reproduce steps.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2024-10-11 17:20 UTC, ideadude commented
I think we can get the LifterLMS team to add a filter for us, so we don't have to use JS to remove this value (kind of hacky).

Do you know where in the LifterLMS code we would want that filter?

2024-10-11 17:53 UTC, MaximilianoRicoTabo commented
What about filter options here @ideadude ? https://github.com/gocodebox/lifterlms/blob/a5e02b8d2fcdcdaf00d9faae54b7ddbd4c6e8c35/includes/admin/views/access-plans/access-plan.php#L274-L277

2025-01-21 23:55 UTC, kimcoleman commented
This filter was added in LifterLMS release this week. We can redo this PR now to use that filter instead. https://github.com/gocodebox/lifterlms/pull/2831

2025-01-21 23:55 UTC, kimcoleman requested changes
This filter was added in LifterLMS release this week. We can redo this PR now to use that filter instead. https://github.com/gocodebox/lifterlms/pull/2831

2025-01-24 20:00 UTC, MaximilianoRicoTabo commented
done @kimcoleman

2025-01-25 20:05 UTC, kimcoleman approved these changes

2025-03-05 13:48 UTC, andrewlimaza approved these changes

2025-03-05 17:40 UTC, merged