BUG: Membership level id and name were missing from Billing Failure …
strangerstudios/paid-memberships-pro pull request #627
Opened 2018-02-09 07:13 UTC by greathmaster

…emails sent to members from webhook

2021-09-16 19:25 UTC, sc0ttkclark approved these changes
Looks good but needs eyes from another team member familiar with this area on whether there's a better solution

2021-09-16 19:36 UTC, dparker1005 requested changes
The user->membership_level line is no longer needed, but the $morder->membership_id change looks good.

2021-09-16 19:36 UTC, dparker1005 commented on services/stripe-webhook.php
> +			$user->membership_level = pmpro_getMembershipLevelForUser($user_id);
```suggestion
```
This change is no longer needed as the user's membership level is now being retrieved in the sendBillingFailureEmail() method as a result of this PR:
https://github.com/strangerstudios/paid-memberships-pro/pull/1586

2021-09-27 19:50 UTC, sc0ttkclark approved these changes

2021-10-01 15:10 UTC, merged